name: descheduler

version: 0.28.0

bundle_version: 0.28.0

img_base: registry.k8s.io/descheduler/descheduler

e2e_cluster_name: descheduler-olm

logo_url: https://github.com/kubernetes-sigs/descheduler/blob/master/assets/logo/descheduler-stacked-color.png?raw=true

# single file manifest used to kubectl apply -f all the required CRDs, configs, services, etc
manifest_upstream: "github.com/kubernetes-sigs/descheduler/kubernetes/deployment?ref=v0.28.0"

# set to "true" if the upstream manifest is meant to be built with kustomize
kustomize_upstream: "true"
