# This file contains configuration which is common to all bundle CSV files.
#
# Some of the CSV fields are required, and while most of these fields are filled
# in automatically by operator-sdk generate bundle, some of the values are
# placeholders and some are left empty.
# See https://github.com/operator-framework/community-operators/blob/master/docs/packaging-required-fields.md
#
# This file contains the values for those fields which should be the same across all versions of the project.
# These values are consumed by the hack/fixup-csv script, which is executed in the Makefile.
#
# TODO(wallrj): some of these fields such as min_ and alm_examples apply to
# ranges of the project versions, so we need to handle that for future
# versions where the min_kubernetes_version may need to be
# incremented or where new fields need to be added to the CRD samples for
# certain versions.

display_name: kueue

description: |
  Kueue is a set of APIs and controller for [job](https://kueue.sigs.k8s.io/docs/concepts/workload/) [queueing](https://kueue.sigs.k8s.io/docs/concepts/#queueing). It is a job-level manager that decides when a job should be admitted to start (as in pods can be created) and when it should stop (as in active pods should be deleted).

  Read the [overview](https://kueue.sigs.k8s.io/docs/overview/) to learn more.

maturity: stable

capabilities: Full Lifecycle

categories:
- Application Runtime

support: The kueue maintainers

repository: https://github.com/kubernetes-sigs/kueue

min_kubernetes_version: 1.19.0-0

keywords:
- job
- queue
- batch

links:
  - name: Documentation
    url: https://kueue.sigs.k8s.io/
  - name: Release Notes
    url: https://github.com/kubernetes-sigs/kueue/releases

provider:
    name: The kueue maintainers
    url: https://kueue.sigs.k8s.io/

maintainers:
- name: The kueue maintainers
  email: sig-scheduling-leads@kubernetes.io

alm_examples:
- apiVersion: ""
  kind: "s"
  metadata:
    name: ""
  spec:
    selfSigned: {}
- apiVersion: ""
  kind: ""
  metadata:
    name: ""
  spec:
    selfSigned: {}

# A list of architectures for which there are Docker images.
# TODO: In future we should add arm (ARCH) and darwin and windows (OS)
# but for now I've only listed the ARCH that were in the original downstream PR:
# https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/434.
#
# See also https://olm.operatorframework.io/docs/advanced-tasks/ship-operator-supporting-multiarch/
architectures:
  - amd64
  - arm64

# A list of Kind.Group which are considered "internal-objects".
# See https://docs.okd.io/4.9/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs
internal_objects:
  - ""
  - ""
