#!/usr/bin/env python3
import yaml
import sys

def find(d, tag):
    if tag in d:
        yield d[tag]
    for k, v in d.items():
        if isinstance(v, dict):
            for i in find(v, tag):
                yield i

stream = open(sys.argv[1], 'r')
data = yaml.safe_load(stream)

for val in find(data, sys.argv[2]):
    print(val)