apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.kueue.x-k8s.io/batch-admin: "true"
  name: kueue-clusterqueue-viewer-role
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - clusterqueues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - clusterqueues/status
  verbs:
  - get
