aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.kueue.x-k8s.io/batch-user: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kueue-batch-user-role
rules: null
